// Code generated by "stringer -type=TokID ../tokens"; DO NOT EDIT.

package tokens

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[begin_single_char_toks-1]
	_ = x[LEFT_PAREN-2]
	_ = x[RIGHT_PAREN-3]
	_ = x[LEFT_BRACE-4]
	_ = x[RIGHT_BRACE-5]
	_ = x[COMMA-6]
	_ = x[DOT-7]
	_ = x[MINUS-8]
	_ = x[PLUS-9]
	_ = x[SEMICOLON-10]
	_ = x[SLASH-11]
	_ = x[STAR-12]
	_ = x[end_single_char_toks-13]
	_ = x[begin_one_two_toks-14]
	_ = x[BANG-15]
	_ = x[BANG_EQUAL-16]
	_ = x[EQUAL-17]
	_ = x[EQUAL_EQUAL-18]
	_ = x[GREATER-19]
	_ = x[GREATER_EQUAL-20]
	_ = x[LESS-21]
	_ = x[LESS_EQUAL-22]
	_ = x[end_one_two_toks-23]
	_ = x[begin_literal_toks-24]
	_ = x[IDENTIFIER-25]
	_ = x[STRING-26]
	_ = x[NUMBER-27]
	_ = x[end_literal_toks-28]
	_ = x[begin_reserved_keywords-29]
	_ = x[AND-30]
	_ = x[CLASS-31]
	_ = x[ELSE-32]
	_ = x[FALSE-33]
	_ = x[FUN-34]
	_ = x[FOR-35]
	_ = x[IF-36]
	_ = x[NIL-37]
	_ = x[OR-38]
	_ = x[PRINT-39]
	_ = x[RETURN-40]
	_ = x[SUPER-41]
	_ = x[THIS-42]
	_ = x[TRUE-43]
	_ = x[VAR-44]
	_ = x[WHILE-45]
	_ = x[end_reserved_keywords-46]
}

const _TokID_name = "EOFbegin_single_char_toksLEFT_PARENRIGHT_PARENLEFT_BRACERIGHT_BRACECOMMADOTMINUSPLUSSEMICOLONSLASHSTARend_single_char_toksbegin_one_two_toksBANGBANG_EQUALEQUALEQUAL_EQUALGREATERGREATER_EQUALLESSLESS_EQUALend_one_two_toksbegin_literal_toksIDENTIFIERSTRINGNUMBERend_literal_toksbegin_reserved_keywordsANDCLASSELSEFALSEFUNFORIFNILORPRINTRETURNSUPERTHISTRUEVARWHILEend_reserved_keywords"

var _TokID_index = [...]uint16{0, 3, 25, 35, 46, 56, 67, 72, 75, 80, 84, 93, 98, 102, 122, 140, 144, 154, 159, 170, 177, 190, 194, 204, 220, 238, 248, 254, 260, 276, 299, 302, 307, 311, 316, 319, 322, 324, 327, 329, 334, 340, 345, 349, 353, 356, 361, 382}

func (i TokID) String() string {
	if i < 0 || i >= TokID(len(_TokID_index)-1) {
		return "TokID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokID_name[_TokID_index[i]:_TokID_index[i+1]]
}
