package tools

import (
	"os"
	"text/template"
)

type PkgTemplateData struct {
	Package    string
	Imports    []string
	Structs    []StructStr
	Interfaces []InterfaceStr
	Methods    []FuncStr
	Functions  []FuncStr
}

const pkgTmpString = `// Code generated by walklox/internal/tools . DO NOT EDIT.

package {{.Package}}

import (
	{{range $imp := .Imports}}"{{$imp}}"{{end}}
)

{{range $ifc := .Interfaces}}
type {{$ifc.Name}} interface { {{range $sig := $ifc.Sigs}}
	{{$sig.Name}}({{$sig.ListParams}}) ({{$sig.ListReturns}}) {{end}}
}
{{end}}
{{range $st := .Structs}}
type {{$st.Name}} struct { {{range $field := $st.Fields}}
	{{$field.Name}} {{$field.Type}} {{end}}
}
{{end}}
{{range $m := .Methods}}
func ({{$m.Receiver}}) {{$m.Name}}({{$m.ListParams}}) ({{$m.ListReturns}}) {
	{{$m.Body}}
}
{{end}}
{{range $f := .Functions}}
func {{$f.Name}}({{$f.ListParams}}) ({{$f.ListReturns}}) {
	{{$f.Body}}
}
{{end}}
`

var pkgTemplate = template.Must(template.New("tmp").Parse(pkgTmpString))

func GeneratePkgFile(f *os.File, ft *PkgTemplateData) {
	pkgTemplate.Execute(f, ft)
}
